# 股票配置文件
stocks:
  - symbol: BABA.US
    watch: true
    initial_action: hold
    threshold: 3.0  # 涨跌幅阈值百分比
  - symbol: INTC.US
    watch: true
    initial_action: hold
    threshold: 3.0
  - symbol: AMD.US
  - symbol: TSLA.US
  - symbol: NVDA.US
  - symbol: NOK.US
  - symbol: MU.US

# LongPort API配置
longport:
  app_key: 
  app_secret: 
  access_token: 
# Deepseek API配置
deepseek:
  api_key: 
  api_url: "https://api.deepseek.com/v1/chat/completions"

# 应用配置
app:
  check_interval: 10  # 检查间隔（秒）
  log_level: "INFO"
  max_position: 50000  # 最大持仓金额
  fallback_to_simulated: true  # 真实下单失败时是否回退到模拟下单

# 交易相关配置
fund_limit: 0  # 交易资金限额（USD），0表示不限制